[project]
name = "src"
version = "0.1.0"
requires-python = "~=3.10.0"
dependencies = [
    "faster-whisper>=1.2.0",
    "hf-xet>=1.1.7",
    "pyperclip>=1.9.0",
    "rich>=14.1.0",
    "streamlit>=1.48.1",
]
